version: '3.2'

services:
  database:
    image: mysql:5.7
    restart: always
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
    networks:
      - node-reverse-proxy

  web-app:    
    build: 
      context: ./nodejs
    container_name: web-app
    networks:
      - node-reverse-proxy
    entrypoint: sh -c './wait-for database:3306 -- echo "Database is up" && npm run start'
    depends_on:
      - database

  nginx:
    image: nginx:1.23.3
    container_name: reverse_proxy
    networks:
      - node-reverse-proxy
    ports:
      - "8080:80"
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    command: [nginx, '-g', 'daemon off;']
    depends_on:
      - web-app    

networks:
  node-reverse-proxy:
    driver: bridge